---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: d9dcb43aca898d38dfd9109229bc3e1088b8a2a8
    app.quarkus.io/build-timestamp: 2023-04-03 - 15:45:40 +0000
  labels:
    app.kubernetes.io/name: camel-quarkus-iot-jvm
    app.kubernetes.io/version: "1.0"
  name: camel-quarkus-iot-jvm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: camel-quarkus-iot-jvm
      app.kubernetes.io/version: "1.0"
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: d9dcb43aca898d38dfd9109229bc3e1088b8a2a8
        app.quarkus.io/build-timestamp: 2023-04-03 - 15:45:40 +0000
      labels:
        app.kubernetes.io/name: camel-quarkus-iot-jvm
        app.kubernetes.io/version: "1.0"
    spec:
      containers:
        - env:
            - name: default
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: zbendhiba/camel-quarkus-iot-jvm:1.0
          imagePullPolicy: Always
          name: camel-quarkus-iot-jvm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: ["ALL"]
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: d9dcb43aca898d38dfd9109229bc3e1088b8a2a8
    app.quarkus.io/build-timestamp: 2023-04-03 - 15:45:40 +0000
  labels:
    app.kubernetes.io/name: camel-quarkus-iot-jvm
    app.kubernetes.io/version: "1.0"
  name: camel-quarkus-iot-jvm
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: camel-quarkus-iot-jvm
    app.kubernetes.io/version: "1.0"
  type: ClusterIP
