---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 789d91df2efbbee991a6c55a5d35b23521b52b21
    app.quarkus.io/build-timestamp: 2023-04-03 - 15:38:59 +0000
  labels:
    app.kubernetes.io/name: camel_quarkus_iot_jvm
    app.kubernetes.io/version: "1.0"
  name: camel_quarkus_iot_jvm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: camel_quarkus_iot_jvm
      app.kubernetes.io/version: "1.0"
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 789d91df2efbbee991a6c55a5d35b23521b52b21
        app.quarkus.io/build-timestamp: 2023-04-03 - 15:38:59 +0000
      labels:
        app.kubernetes.io/name: camel_quarkus_iot_jvm
        app.kubernetes.io/version: "1.0"
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: zbendhiba/camel_quarkus_iot_jvm:1.0
          imagePullPolicy: Always
          name: camel_quarkus_iot_jvm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 789d91df2efbbee991a6c55a5d35b23521b52b21
    app.quarkus.io/build-timestamp: 2023-04-03 - 15:38:59 +0000
  labels:
    app.kubernetes.io/name: camel_quarkus_iot_jvm
    app.kubernetes.io/version: "1.0"
  name: camel_quarkus_iot_jvm
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: camel_quarkus_iot_jvm
    app.kubernetes.io/version: "1.0"
  type: ClusterIP
